USE [master]
GO

/****** Object:  Database [ContainerDb]    Script Date: 12/13/2019 8:12:50 AM ******/
CREATE DATABASE [ContainerDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContainerDb', FILENAME = N'/var/opt/mssql/data/ContainerDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContainerDb_log', FILENAME = N'/var/opt/mssql/data/ContainerDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContainerDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContainerDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContainerDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContainerDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContainerDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContainerDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContainerDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContainerDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContainerDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContainerDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContainerDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContainerDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContainerDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContainerDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContainerDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContainerDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContainerDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContainerDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContainerDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContainerDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContainerDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContainerDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContainerDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContainerDb] SET RECOVERY FULL 
GO

ALTER DATABASE [ContainerDb] SET  MULTI_USER 
GO

ALTER DATABASE [ContainerDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContainerDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContainerDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContainerDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContainerDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContainerDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ContainerDb] SET  READ_WRITE 
GO


